version: '3'
services:
  publisher:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/usr/local/bin/yarn", "dev:publisher"]
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./src:/app/src
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/usr/local/bin/yarn", "dev:worker"]
    links:
      - "publisher:pub"
    depends_on:
      - publisher
    environment:
      - PUB_PORT=3000
      - PUB_HOST=pub
    volumes:
      - ./src:/app/src
