version: '3'
services:
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - "./redis-data:/data"
  publisher:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/usr/local/bin/yarn", "dev:publisher"]
    links:
      - "redis:redis"
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./src:/app/src
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/usr/local/bin/yarn", "dev:worker"]
    links:
      - "publisher:pub"
      - "redis:redis"
    depends_on:
      - publisher
      - redis
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./temp:/app/temp
