---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seasidefm
  name: video-intake
  labels:
    app: video-intake
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-intake
  template:
    metadata:
      labels:
        app: video-intake
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: video-worker
          image: registry.dougflynn.dev/video-intake
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis
            - name: UPLOAD_BUCKET
              value: raw-streams
            - name: PROCESSED_BUCKET
              value: ready-to-stream
---
apiVersion: v1
kind: Service
metadata:
  name: video-intake
  namespace: seasidefm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: video-intake
#---
#kind: Ingress
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: video-intake
#  namespace: seasidefm
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: web
#
#spec:
#  rules:
#    - host: uploads.seaside.fm
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: video-intake
#                port:
#                  number: 80
