---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seasidefm
  name: video-worker
  labels:
    app: video-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-worker
  template:
    metadata:
      labels:
        app: video-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: video-worker
          image: registry.dougflynn.dev/video-worker
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/temp
              name: video-worker-storage
          env:
            - name: REDIS_HOST
              value: redis
            - name: UPLOAD_BUCKET
              value: raw-streams
            - name: PROCESSED_BUCKET
              value: ready-to-stream
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: minio-worker-secret
                  key: MINIO_ENDPOINT
            - name: MINIO_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-worker-secret
                  key: MINIO_KEY
            - name: MINIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: minio-worker-secret
                  key: MINIO_SECRET
      volumes:
        # Each worker needs some storage for processing a video with ffmpeg
        - name: video-worker-storage
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: longhorn
                resources:
                  requests:
                    storage: 15Gi
                    numberOfReplicas: "1"
