---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seasidefm
  name: video-worker
  labels:
    app: video-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-worker
  template:
    metadata:
      labels:
        app: video-worker
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
      volumes:
        # Each worker needs some storage for processing a video with ffmpeg
        - name: video-worker-storage
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: longhorn
                resources:
                  requests:
                    storage: 15Gi
                    numberOfReplicas: "1"
