---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seasidefm
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      restartPolicy: Always
      containers:
        - name: minio
          image: quay.io/minio/minio
          imagePullPolicy: IfNotPresent
          args: ["server", "/data", "--console-address", ":9001"]
          volumeMounts:
            - name: minio-volume
              mountPath: /data
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
      volumes:
        - name: minio-volume
          persistentVolumeClaim:
            claimName: minio-object-storage