---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: seasidefm
  name: minio-object-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi